version: '2'
services:
  web:
    image: feelingfree/rpi-alpine-node:4.4.5
    volumes:
      - "/loca/work-directory/:/app"
    working_dir: /app
    restart: always
    expose:
     - "3000"
    ports:
      - "3000:3000"
    command: node app.js